version: '3.4'
services:
  #PHP Service
  app:
    image: snipe:v1
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0
    volumes:
      - "./data/lib:/var/lib/mysql"
      - "./data/log:/var/log/mysql"
    ports:
      - 3301:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
